### ISSUE TITLE
Html Links

### ISSUE THREAD

**Issue by negue** [porokoro/paperboy#2]
I tried to add Html-Links to an entry, but nothing happens on them :(

**Comment by porokoro** [comment]
When implementing HTML rendering I didn't think about links. It was supposed to be used for **bold**, **italic**, **underlined** and so on. I will enable the handling of links for the next feature release.

For the case that you want to open the link inside an app itself instead of starting the default app (most probably a browser), you can define an **intent filter** with a **custom scheme** for the desired Activity.

**Comment by negue** [comment]
Oh thats great, thx :)
